### ISSUE TITLE
Contribution

### ISSUE THREAD

**Issue by AdelKS** [Jannik2099/pms-utils#1]
Hello!

I found this project through @thesamesam's activity hehe. And it looks like we have some shared interests. I wanted to have a go at dependency resolution, and I had to write my own routines for PMS and this exactly what this project aims to offer.

The routines are part of my dep solver project https://github.com/adelKS/quantumresolver:  it also uses `C++20` and the `meson` build system. If you have a look at its readme, so far there's the `quantum` cli program which offers a mix between `equery y [atom]` and `emerge -qpvO [atom]`. That should give an idea on which routines were implemented for it to work.

So maybe we can collaborate so I can rework and transfer the other routines I wrote to this library and make my project depend on it. So my own project focuses only on the dependency resolution.

One example of discussion: I took a quick look at what you wrote for version comparison, I wanted to use `std::strong_ordering` but in the end preferred specific optimizations for each case, using [lexicographical_compare_three_way](https://en.cppreference.com/w/cpp/algorithm/lexicographical_compare_three_way) with an internal representation that works with it, so it could leverage SIMD instructions (my intent is to write the fastest dependency resolver I could come up with). See [ebuild_version.h](https://github.com/AdelKS/QuantumResolver/blob/main/include/quantum-resolver/core/ebuild_version.h) and [ebuild_version.cpp](https://github.com/AdelKS/QuantumResolver/blob/main/src/core/ebuild_version.cpp)

**Comment by Jannik2099** [comment]
Long ago, this project was meant to be a dependency resolver! Then it got shelved :P

My idea was to translate PMS DEPEND expressions into [z3](https://github.com/Z3Prover/z3) expressions, as I'm reasonably certain that's faster (and more importantly, easier to assert for correctness) than anything one would implement from scratch with a dependency structure as complex as PMS.

Alas, I don't plan on doing dep resolving myself anytime soon, so good luck with that effort.

I am very excited about your proposal though, please hit me with any algorithm / utility that you deem useful to work with PMS-related stuff.

I don't even install a C++ API yet, though I don't expect the AST types to change any further.

**Comment by AdelKS** [comment]
Thanks for your feedback,

I did not know the z3 library, I will need to delve into it for a bit first. I also got redirected to CUDF solvers (see this bug ticket https://bugs.gentoo.org/841206).

I used my own representation to everything for a few reasons:
- Better understand and and get an intuition to the PMS
- Have 1-to-1 correspondence with Gentoo's specific problem. I understand that if an another representation is equivalent or more generic then it's fine.
- I can feel comfortable while exploring around to understand better the dependency problem, without adding the extra layer of abstraction from another representation
  - simplify the dependencies and various ways and represent them graphically

The biggest chunk that this lib needs is to have some kind of in-memory representation of a repository: what ebuilds are available and how the profile and user settings affect their USE flags and visibility. Which should be orthogonal to dependency representation. Is it something you see this lib offering ? It's definitely needed for dependency resolving. I already implemented (nearly?) all of that, but far from being perfect (I doubt I can ever be satisfied on that end) and having someone to discuss stuff with would definitely make things better.

**Comment by Jannik2099** [comment]
This project aims to implement anything PMS-related, and both repo and profile layouts are described in PMS.
So I'll definitely work on those features.

**Comment by AdelKS** [comment]
Since my project is farther in the development, it can already do all of that. It is only missing handling several overlays. I am not sure how to proceed, maybe I can open an RFC exposing the approach I took so far, and go from there to come up with a satisfactory POO representation

**Comment by Jannik2099** [comment]
> It is only missing handling several overlays

My idea is to provide some class (`ProfileViewer`?) that assembles a `pms_utils::repo::Repository` for each registered repo, and provides a view over the effective available packages as per overlay priority, repo package.mask etc.

**Comment by AdelKS** [comment]
I took some more time to delve into my code: given my original scope, I went for an approach where the code is deeply integrated with the machine's current profile and user settings, and "digests" the information so it simplifies how to think about dependency resolution: 
- All overlays are merged into one single repository `Repo`
- `Repo` contains a list of `Package`s
- `Package` contains a list of `Ebuild`s ordered by version
  - Not implemented: same-version is ordered by overlay priority
- Each `Ebuild` instance knows
  - If it's currently installed
  - Its metadata
  - Can make an AST of its depstrings when queried for it 
  -  the state of its flags with respect to the current system: 
    - What flags has it been installed with
    - Which flags are currently activated by the profile, which ones are different from the installed
    - Which ones are forced, masked
 - The `Profile`'s information is distributed to the packages where applicable, and the class I wrote for it only keeps in the end information about the global useflag states and what are the use expands. The class becomes irrelevant during dependency resolution: everything needed is in the `Repo` instance.
 - On top of that, the library uses integers internally instead of strings for package names and useflag names, to shortcut all the hashing when querying stuff during dependency resolution.

Now, I think I can PR a `Profile` class that can be built by giving it the profile folder and will contain everything a profile contains.

**Comment by Jannik2099** [comment]
> Each Ebuild instance knows

I'm currently working on giving `repo::Ebuild` a `.metadata()` method that essentially returns a struct of the md5-cache entries.

I won't put any of the "local state related stuff" (i.e. If it's currently installed) into `Ebuild` - the `repo` namespace is intended for working with repositories, not providing an "evaluated" view against the current system - that will come later.

All of that is related to `/var/db/pkg`, which iirc is called VDB? portdb? somewhere in pms. I'll tackle that at some later point in time.

**Comment by AdelKS** [comment]
> I won't put any of the "local state related stuff" (i.e. If it's currently installed) into Ebuild - the repo namespace is intended for working with repositories, not providing an "evaluated" view against the current system - that will come later.

Yeah it makes sense, your scope is to offer tools to handle PMS related things, so it's better to stick with the PMS' structure.

As a future user of this lib, if I can get structured metadata in string format, about everything I need, that would be amazing.

> Now, I think I can PR a Profile class that can be built by giving it the profile folder and will contain everything a profile contains.

I suppose you don't have too much free time for this project too, and I think it would be amazing for me if the work I did doesn't get thrown in the bin haha. What do you think of letting me offer a `Profile` class ? First I will make a draft of header for that class first.

**Comment by Jannik2099** [comment]
Thanks for the offer, I have thought about it and I think I won't be any big feature PRs for now - simply because I'm still very unsure about the overall API design, and I want it to be suitable to be consumed by portage first and foremost.

What would be of great help however is if you could formulate your API needs in a mockup header or something.

**Comment by AdelKS** [comment]
It's absolutely okay ! And I understand you very well. 

I'll take some time to make what I did into a library, and that will makes things clearer for me on what would my needs be. And maybe it can inspire you or you can get some code out from it.

If you think you can use an extra brain or a pair of hands I'm around here and on IRC. 

I'll close this issue and open another about my needs when I'll get to it !
